import { pgTable, uuid, varchar, text, date, boolean, timestamp, integer, decimal } from 'drizzle-orm/pg-core';
import { authProvider, gender, verificationStatus, onlineStatus } from '../enums';

export const astrologers = pgTable('astrologers', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }).unique().notNull(),
  phone: varchar('phone', { length: 20 }).unique(),
  password: varchar('password', { length: 255 }),
  avatar: text('avatar'),
  gender: gender('gender'),
  dateOfBirth: date('date_of_birth'),
  authProvider: authProvider('auth_provider').notNull().default('email'),
  authProviderId: varchar('auth_provider_id', { length: 255 }),
  bio: text('bio'),
  experience: integer('experience').notNull().default(0),
  specialization: text('specialization').array().notNull().default([]),
  languages: text('languages').array().notNull().default([]),
  skills: text('skills').array().notNull().default([]),
  pricePerMin: decimal('price_per_min', { precision: 10, scale: 2 }).notNull().default('0'),
  rating: decimal('rating', { precision: 3, scale: 2 }).notNull().default('0'),
  totalReviews: integer('total_reviews').notNull().default(0),
  totalCalls: integer('total_calls').notNull().default(0),
  totalEarnings: decimal('total_earnings', { precision: 12, scale: 2 }).notNull().default('0'),
  verificationStatus: verificationStatus('verification_status').notNull().default('pending'),
  verificationDoc: text('verification_doc').array(),
  verificationNote: text('verification_note'),
  onlineStatus: onlineStatus('online_status').notNull().default('offline'),
  isActive: boolean('is_active').notNull().default(true),
  fcmToken: text('fcm_token'),
  lastLoginAt: timestamp('last_login_at'),
  onboardingCompleted: boolean('onboarding_completed').notNull().default(false),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  deletedAt: timestamp('deleted_at'),
});
